### ISSUE TITLE
TypeError: ('Bad input argument to theano function with name "holographic_memory.py:84"

### ISSUE THREAD

**Issue by SeekPoint** [mohammadpz/Associative_LSTM#3]
envy@ub1404:~/os_pri/github/Associative_LSTM$ python holographic_memory.py 
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "holographic_memory.py", line 94, in <module>
    MEM = write_func(KEYS, VALUES)
  File "/home/envy/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 786, in **call**
    allow_downcast=s.allow_downcast)
  File "/home/envy/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 139, in filter
    raise TypeError(err_msg, data)
TypeError: ('Bad input argument to theano function with name "holographic_memory.py:84"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".', array([[-0.33998727,  0.77906697,  0.06991387, ..., -0.98946589,
        -0.83468061,  0.89153633],
       [-0.63970228,  0.8195924 ,  0.9473632 , ...,  0.16236229,
         0.94564315,  0.97183497],
       [ 0.67610139,  0.99756132,  0.8097881 , ..., -0.69396546,
         0.8336102 , -0.98980493],
       ..., 
       [ 0.27303741,  0.97723419, -0.99634828, ..., -0.42349166,
         0.35726541,  0.99777589],
       [ 0.56724025,  0.79452556,  0.90919262, ..., -0.50166936,
        -0.97753518, -0.96124023],
       [ 0.28472163,  0.10105307, -0.1343447 , ..., -0.51666857,
         0.95856671, -0.89232788]]))
envy@ub1404:~/os_pri/github/Associative_LSTM$

**Comment by mpezeshki** [comment]
Using `THEANO_FLAGS='floatX=float32' python holographic_memory.py` should fix the problem.

**Comment by SeekPoint** [comment]
I tried:

envy@ub1404:~/os_pri/github/Associative_LSTM$ THEANO_FLAGS='floatX=float32' python holographic_memory.py
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "holographic_memory.py", line 94, in <module>
    MEM = write_func(KEYS, VALUES)
  File "/home/envy/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 786, in **call**
    allow_downcast=s.allow_downcast)
  File "/home/envy/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 139, in filter
    raise TypeError(err_msg, data)
TypeError: ('Bad input argument to theano function with name "holographic_memory.py:84"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".', array([[ 0.85184374,  0.82000731,  0.99867008, ...,  0.43216262,
        -0.28698177, -0.26221031],
       [ 0.8731134 , -0.26070533, -0.91038367, ..., -0.06170114,
        -0.19895874, -0.13945744],
       [ 0.3685904 , -0.99917839, -0.90257495, ...,  0.47001036,
         0.66174286,  0.12531638],
       ..., 
       [-0.81111444,  0.94144517, -0.90505509, ...,  0.73322565,
         0.8069545 ,  0.94837876],
       [ 0.46073917,  0.40346909, -0.98421055, ..., -0.70648842,
         0.2854518 ,  0.53658445],
       [ 0.9140164 ,  0.82759999, -0.52525026, ...,  0.36035819,
         0.03019263,  0.82799066]]))
envy@ub1404:~/os_pri/github/Associative_LSTM$ 

and

envy@ub1404:~/os_pri/github/Associative_LSTM$ THEANO_FLAGS='allow_input_downcast=True' python holographic_memory.py
/home/envy/.local/lib/python2.7/site-packages/theano/configdefaults.py:1686: UserWarning: Theano does not recognise this flag: allow_input_downcast
  warnings.warn('Theano does not recognise this flag: {0}'.format(key))
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "holographic_memory.py", line 94, in <module>
    MEM = write_func(KEYS, VALUES)
  File "/home/envy/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 786, in **call**
    allow_downcast=s.allow_downcast)
  File "/home/envy/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 139, in filter
    raise TypeError(err_msg, data)
TypeError: ('Bad input argument to theano function with name "holographic_memory.py:84"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".', array([[ 0.55820402, -0.99933052, -0.58131817, ..., -0.99162348,
         0.97391971,  0.99976266],
       [-0.64940681, -0.06587449, -0.49446634, ...,  0.76723741,
        -0.99872607,  0.57148139],
       [ 0.98469854,  0.98922329,  0.68558021, ..., -0.54050539,
        -0.97274425,  0.13653712],
       ..., 
       [-0.86314311, -0.78690848, -0.95348783, ...,  0.87118976,
         0.84511147, -0.47139609],
       [ 0.99752764, -0.66803953,  0.84460468, ..., -0.97220982,
         0.45180846,  0.22152956],
       [-0.54236742,  0.05867093, -0.97811148, ...,  0.88242457,
         0.93022328, -0.98206891]]))
envy@ub1404:~/os_pri/github/Associative_LSTM$

**Comment by loveJasmine** [comment]
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ bash run_msr_sort.sh 
========begin to sort dataset========	
cp /media/envy/data1t/dataset/raw/savedisk/msr.dep.100.vocab.t7 /media/envy/data1t/dataset/raw/savedisk/msr.dep.100.sort.vocab.t7	
[sort algorithm] = sort batches!	
write [train] line count = 50000
write [train] line count = 100000
write [train] line count = 150000
write [train] line count = 200000
write [train] line count = 250000
write [train] line count = 300000
write [train] line count = 350000
write [train] line count = 400000
write [train] line count = 450000
write [train] line count = 500000
write [train] line count = 550000
write [train] line count = 600000
write [train] line count = 650000
write [train] line count = 700000
write [train] line count = 750000
write [train] line count = 800000
write [train] line count = 850000
write [train] line count = 900000
write [train] line count = 950000
write [train] line count = 1000000
write [train] line count = 1050000
write [train] line count = 1100000
write [train] line count = 1150000
write [train] line count = 1200000
write [train] line count = 1250000
write [train] line count = 1300000
write [train] line count = 1350000
write [train] line count = 1400000
write [train] line count = 1450000
write [train] line count = 1500000
write [train] line count = 1550000
write [train] line count = 1600000
write [train] line count = 1650000
write [train] line count = 1700000
write [train] line count = 1750000
write [train] line count = 1800000
write [train] line count = 1850000
write [train] line count = 1900000
write [train] line count = 1950000
write [train] line count = 2000000
write [train] line count = 2050000
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139853053990784:
  #000: ../../../src/H5Dio.c line 161 in H5Dread(): selection+offset not within extent
    major: Dataspace
    minor: Out of range
/home/envy/torch/install/bin/luajit: /home/envy/torch/install/share/lua/5.1/hdf5/dataset.lua:160: HDF5DataSet:partial() - failed reading data from [HDF5DataSet (83886084 /train/x_data DATASET)]
stack traceback:
	[C]: in function 'assert'
	/home/envy/torch/install/share/lua/5.1/hdf5/dataset.lua:160: in function 'partial'
	./sorthdf5.lua:107: in function 'writeSplit'
	./sorthdf5.lua:32: in function 'sortHDF5'
	sort_large_hdf5.lua:35: in function 'main'
	sort_large_hdf5.lua:40: in main chunk
	[C]: in function 'dofile'
	...envy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
envy@ub1404:~/os_pri/github/td-treelstm/scripts$

**Comment by SeekPoint** [comment]
it doesn't work yet
